import { Country } from "../types/country";

export const countries:Country[]=[
    {
        id:"en",
        name:"English",
        icon:"./assets/gb.svg"
    },
    {
        id:"be",
        name:"Беларуская",
        icon:"./assets/by.svg"
    },
    {
        id:"fr",
        name:"Français",
        icon:"./assets/fr.svg"
    },
    {
        id:"hr",
        name:"Hrvatski",
        icon:"./assets/hr.svg"
    },
    {
        id:"it",
        name:"Italiano",
        icon:"./assets/it.svg"
    },
    {
        id:"ja",
        name:"日本語",
        icon:"./assets/jp.svg"
    },
    {
        id:"pl",
        name:"Polski",
        icon:"./assets/pl.svg"
    },
    {
        id:"ru",
        name:"Русский",
        icon:"./assets/ru.svg"
    },
    {
        id:"uk",
        name:"Україньска",
        icon:"./assets/ua.svg"
    },
    {
        id:"de",
        name:"Deutsch",
        icon:"./assets/de.svg"
    },
    {
        id:"es",
        name:"Español",
        icon:"./assets/es.svg"
    },
]